"""
Postgres database layer — raw SQL, no ORM.
All dates stored as TEXT (ISO 8601: YYYY-MM-DD).
"""
import json
from datetime import datetime
from typing import Optional

import psycopg
from psycopg.rows import dict_row


class Database:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self._init()

    def _conn(self) -> psycopg.Connection:
        return psycopg.connect(self.database_url, row_factory=dict_row)

    def _init(self):
        with self._conn() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS settings (
                    key   TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS sleep_nights (
                    date                TEXT PRIMARY KEY,
                    sleep_score         DOUBLE PRECISION,
                    continuity_score    DOUBLE PRECISION,
                    efficiency_score    DOUBLE PRECISION,
                    rem_score           DOUBLE PRECISION,
                    n3_score            DOUBLE PRECISION,
                    sleep_span_sec      INTEGER,
                    asleep_sec          INTEGER,
                    efficiency_pct      DOUBLE PRECISION,
                    interruptions_total INTEGER,
                    interruptions_long  INTEGER,
                    rem_pct             DOUBLE PRECISION,
                    deep_pct            DOUBLE PRECISION,
                    sleep_start         TEXT,
                    sleep_end           TEXT,
                    raw_json            TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS nightly_recovery (
                    date                    TEXT PRIMARY KEY,
                    rmssd                   DOUBLE PRECISION,
                    rri                     DOUBLE PRECISION,
                    recovery_indicator      INTEGER,
                    recovery_sub_level      INTEGER,
                    ans_status              DOUBLE PRECISION,
                    resp_interval_ms        DOUBLE PRECISION,
                    raw_json                TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS activity_days (
                    date            TEXT PRIMARY KEY,
                    steps           INTEGER,
                    calories        DOUBLE PRECISION,
                    met_minutes     DOUBLE PRECISION,
                    active_calories DOUBLE PRECISION,
                    raw_json        TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS hr_days (
                    date        TEXT PRIMARY KEY,
                    resting_hr  DOUBLE PRECISION,
                    avg_hr      DOUBLE PRECISION,
                    raw_json    TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS sync_log (
                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    synced_at    TEXT NOT NULL,
                    nights_added INTEGER DEFAULT 0,
                    status       TEXT DEFAULT 'ok',
                    message      TEXT
                )
            """)

    def save_token(self, access_token: str, polar_user_id: int):
        with self._conn() as conn:
            conn.execute(
                """
                INSERT INTO settings (key, value) VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """,
                ("access_token", access_token),
            )
            conn.execute(
                """
                INSERT INTO settings (key, value) VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """,
                ("polar_user_id", str(polar_user_id)),
            )

    def get_token(self) -> Optional[dict]:
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT key, value FROM settings WHERE key IN ('access_token', 'polar_user_id')"
            ).fetchall()
        d = {r["key"]: r["value"] for r in rows}
        if "access_token" not in d or "polar_user_id" not in d:
            return None
        return {"access_token": d["access_token"], "polar_user_id": int(d["polar_user_id"])}

    def clear_token(self):
        with self._conn() as conn:
            conn.execute("DELETE FROM settings WHERE key IN ('access_token', 'polar_user_id')")

    def upsert_sleep_night(self, night: dict):
        import re

        def parse_dur(s):
            if not s:
                return None
            h = m = sec = 0
            mh = re.search(r"(\d+)H", s)
            mm = re.search(r"(\d+)M", s)
            ms = re.search(r"(\d+)S", s)
            if mh: h = int(mh.group(1))
            if mm: m = int(mm.group(1))
            if ms: sec = int(ms.group(1))
            return h * 3600 + m * 60 + sec

        d = night.get("date") or night.get("night")
        sc = night.get("score", {}) or {}
        ev = night.get("sleepResultPolarUser", night.get("evaluation", {})) or {}
        hg = night.get("hypnogram", ev.get("hypnogram", {})) or {}
        phases = ev.get("phaseDurations", hg.get("phaseDurations", {})) or {}
        ints = ev.get("interruptions", {}) or {}
        analysis = ev.get("analysis", {}) or {}

        with self._conn() as conn:
            conn.execute("""
                INSERT INTO sleep_nights
                (date, sleep_score, continuity_score, efficiency_score, rem_score, n3_score,
                 sleep_span_sec, asleep_sec, efficiency_pct,
                 interruptions_total, interruptions_long, rem_pct, deep_pct,
                 sleep_start, sleep_end, raw_json)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    sleep_score = EXCLUDED.sleep_score,
                    continuity_score = EXCLUDED.continuity_score,
                    efficiency_score = EXCLUDED.efficiency_score,
                    rem_score = EXCLUDED.rem_score,
                    n3_score = EXCLUDED.n3_score,
                    sleep_span_sec = EXCLUDED.sleep_span_sec,
                    asleep_sec = EXCLUDED.asleep_sec,
                    efficiency_pct = EXCLUDED.efficiency_pct,
                    interruptions_total = EXCLUDED.interruptions_total,
                    interruptions_long = EXCLUDED.interruptions_long,
                    rem_pct = EXCLUDED.rem_pct,
                    deep_pct = EXCLUDED.deep_pct,
                    sleep_start = EXCLUDED.sleep_start,
                    sleep_end = EXCLUDED.sleep_end,
                    raw_json = EXCLUDED.raw_json
            """, (
                d,
                sc.get("sleep") or sc.get("sleepScore"),
                sc.get("continuity") or sc.get("continuityScore"),
                sc.get("efficiency") or sc.get("efficiencyScore"),
                sc.get("rem") or sc.get("remScore"),
                sc.get("n3") or sc.get("n3Score"),
                parse_dur(ev.get("sleepSpan") or hg.get("sleepSpan")),
                parse_dur(ev.get("asleepDuration") or hg.get("asleepDuration")),
                analysis.get("efficiencyPercent") or ev.get("efficiencyPercent"),
                ints.get("totalCount") or ints.get("total"),
                ints.get("longCount") or ints.get("long"),
                phases.get("remPercentage"),
                phases.get("deepPercentage"),
                hg.get("sleepStart") or ev.get("sleepStart"),
                hg.get("sleepEnd") or ev.get("sleepEnd"),
                json.dumps(night),
            ))

    def upsert_recovery(self, day: str, rec: dict):
        with self._conn() as conn:
            conn.execute("""
                INSERT INTO nightly_recovery
                (date, rmssd, rri, recovery_indicator, recovery_sub_level,
                 ans_status, resp_interval_ms, raw_json)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    rmssd = EXCLUDED.rmssd,
                    rri = EXCLUDED.rri,
                    recovery_indicator = EXCLUDED.recovery_indicator,
                    recovery_sub_level = EXCLUDED.recovery_sub_level,
                    ans_status = EXCLUDED.ans_status,
                    resp_interval_ms = EXCLUDED.resp_interval_ms,
                    raw_json = EXCLUDED.raw_json
            """, (
                day,
                rec.get("meanNightlyRecoveryRmssd") or rec.get("rmssd"),
                rec.get("meanNightlyRecoveryRri") or rec.get("rri"),
                rec.get("recoveryIndicator"),
                rec.get("recoveryIndicatorSubLevel"),
                rec.get("ansStatus"),
                rec.get("meanNightlyRecoveryRespirationInterval") or rec.get("respirationInterval"),
                json.dumps(rec),
            ))

    def upsert_activity(self, act: dict):
        day = act.get("date") or act.get("created")[:10]
        summary = act.get("summary", act)
        with self._conn() as conn:
            conn.execute("""
                INSERT INTO activity_days
                (date, steps, calories, met_minutes, active_calories, raw_json)
                VALUES (%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    steps = EXCLUDED.steps,
                    calories = EXCLUDED.calories,
                    met_minutes = EXCLUDED.met_minutes,
                    active_calories = EXCLUDED.active_calories,
                    raw_json = EXCLUDED.raw_json
            """, (
                day,
                summary.get("stepCount") or summary.get("steps"),
                summary.get("calories"),
                summary.get("dailyMetMinutes") or summary.get("metMinutes"),
                summary.get("activeCalories"),
                json.dumps(act),
            ))

    def upsert_hr_day(self, day: str, resting_hr: float, avg_hr: float, raw: dict):
        with self._conn() as conn:
            conn.execute("""
                INSERT INTO hr_days (date, resting_hr, avg_hr, raw_json)
                VALUES (%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    resting_hr = EXCLUDED.resting_hr,
                    avg_hr = EXCLUDED.avg_hr,
                    raw_json = EXCLUDED.raw_json
            """, (day, resting_hr, avg_hr, json.dumps(raw)))

    def log_sync(self, nights_added: int = 0, status: str = "ok", message: str = None):
        with self._conn() as conn:
            conn.execute(
                "INSERT INTO sync_log (synced_at, nights_added, status, message) VALUES (%s,%s,%s,%s)",
                (datetime.utcnow().isoformat(), nights_added, status, message),
            )

    def last_sync(self) -> Optional[str]:
        with self._conn() as conn:
            row = conn.execute(
                "SELECT synced_at FROM sync_log WHERE status='ok' ORDER BY id DESC LIMIT 1"
            ).fetchone()
        return row["synced_at"] if row else None

    def get_nights(self, days: int = 30) -> list:
        with self._conn() as conn:
            rows = conn.execute("""
                SELECT
                    s.date,
                    s.sleep_score,    s.continuity_score, s.efficiency_score,
                    s.rem_score,      s.n3_score,
                    s.sleep_span_sec, s.asleep_sec,       s.efficiency_pct,
                    s.interruptions_total, s.interruptions_long,
                    s.rem_pct,        s.deep_pct,
                    s.sleep_start,    s.sleep_end,
                    r.rmssd,          r.rri,
                    r.recovery_indicator, r.recovery_sub_level,
                    r.ans_status,     r.resp_interval_ms,
                    a.steps,          a.calories,         a.met_minutes,
                    h.resting_hr,     h.avg_hr
                FROM sleep_nights s
                LEFT JOIN nightly_recovery r ON r.date = s.date
                LEFT JOIN activity_days    a ON a.date = s.date
                LEFT JOIN hr_days          h ON h.date = s.date
                ORDER BY s.date DESC
                LIMIT %s
            """, (days,)).fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_hypnogram_events(self, days: int = 30) -> list:
        """Returns raw sleep_start + hypnogram state changes for interruption analysis."""
        with self._conn() as conn:
            rows = conn.execute("""
                SELECT date, sleep_start, sleep_end, raw_json
                FROM sleep_nights
                ORDER BY date DESC LIMIT %s
            """, (days,)).fetchall()
        return [dict(r) for r in rows]
