"""
Postgres database layer — raw SQL, no ORM.

Principles:
- Keep official Polar payloads as raw JSON for future re-parsing.
- Store dashboard-ready columns only when their source and units are clear.
- Do not fabricate unsupported metrics. Unknown values stay NULL.
"""
import json
from datetime import datetime
from typing import Optional

import psycopg
from psycopg.rows import dict_row


class Database:
    def __init__(self, database_url: str):
        self.database_url = database_url
        self._init()

    def _conn(self) -> psycopg.Connection:
        return psycopg.connect(self.database_url, row_factory=dict_row)

    def _init(self):
        with self._conn() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS settings (
                    key   TEXT PRIMARY KEY,
                    value TEXT NOT NULL
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS sleep_nights (
                    date                TEXT PRIMARY KEY,
                    sleep_score         DOUBLE PRECISION,
                    continuity_score    DOUBLE PRECISION,
                    efficiency_score    DOUBLE PRECISION,
                    rem_score           DOUBLE PRECISION,
                    n3_score            DOUBLE PRECISION,
                    sleep_span_sec      INTEGER,
                    asleep_sec          INTEGER,
                    efficiency_pct      DOUBLE PRECISION,
                    interruptions_total INTEGER,
                    interruptions_long  INTEGER,
                    rem_pct             DOUBLE PRECISION,
                    deep_pct            DOUBLE PRECISION,
                    sleep_start         TEXT,
                    sleep_end           TEXT,
                    raw_json            TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS nightly_recovery (
                    date                    TEXT PRIMARY KEY,
                    rmssd                   DOUBLE PRECISION,
                    rri                     DOUBLE PRECISION,
                    recovery_indicator      INTEGER,
                    recovery_sub_level      INTEGER,
                    ans_status              DOUBLE PRECISION,
                    resp_interval_ms        DOUBLE PRECISION,
                    raw_json                TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS activity_days (
                    date            TEXT PRIMARY KEY,
                    steps           INTEGER,
                    calories        DOUBLE PRECISION,
                    met_minutes     DOUBLE PRECISION,
                    active_calories DOUBLE PRECISION,
                    raw_json        TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS hr_days (
                    date        TEXT PRIMARY KEY,
                    resting_hr  DOUBLE PRECISION,
                    avg_hr      DOUBLE PRECISION,
                    raw_json    TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS cardio_load_days (
                    date               TEXT PRIMARY KEY,
                    cardio_load_status TEXT,
                    cardio_load        DOUBLE PRECISION,
                    strain             DOUBLE PRECISION,
                    tolerance          DOUBLE PRECISION,
                    cardio_load_ratio  DOUBLE PRECISION,
                    raw_json           TEXT
                )
            """)
            conn.execute("""
                CREATE TABLE IF NOT EXISTS sync_log (
                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    synced_at    TEXT NOT NULL,
                    nights_added INTEGER DEFAULT 0,
                    status       TEXT DEFAULT 'ok',
                    message      TEXT
                )
            """)

            self._add_column(conn, "sleep_nights", "total_interruption_sec", "INTEGER")
            self._add_column(conn, "sleep_nights", "short_interruption_sec", "INTEGER")
            self._add_column(conn, "sleep_nights", "long_interruption_sec", "INTEGER")
            self._add_column(conn, "sleep_nights", "wake_count", "INTEGER")
            self._add_column(conn, "sleep_nights", "sleep_cycles", "INTEGER")
            self._add_column(conn, "sleep_nights", "continuity_raw", "DOUBLE PRECISION")

            self._add_column(conn, "nightly_recovery", "resp_rate_bpm", "DOUBLE PRECISION")
            self._add_column(conn, "nightly_recovery", "heart_rate_avg", "DOUBLE PRECISION")
            self._add_column(conn, "nightly_recovery", "ans_charge_status", "INTEGER")

            self._add_column(conn, "activity_days", "daily_activity", "DOUBLE PRECISION")
            self._add_column(conn, "activity_days", "distance_from_steps", "DOUBLE PRECISION")
            self._add_column(conn, "activity_days", "inactivity_alert_count", "INTEGER")

    @staticmethod
    def _add_column(conn, table: str, column: str, coltype: str):
        conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column} {coltype}")

    # ── Settings / token ───────────────────────────────────────────────────

    def save_token(self, access_token: str, polar_user_id: int):
        with self._conn() as conn:
            conn.execute(
                """
                INSERT INTO settings (key, value) VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """,
                ("access_token", access_token),
            )
            conn.execute(
                """
                INSERT INTO settings (key, value) VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """,
                ("polar_user_id", str(polar_user_id)),
            )

    def get_token(self) -> Optional[dict]:
        with self._conn() as conn:
            rows = conn.execute(
                "SELECT key, value FROM settings WHERE key IN ('access_token', 'polar_user_id')"
            ).fetchall()
        d = {r["key"]: r["value"] for r in rows}
        if "access_token" not in d or "polar_user_id" not in d:
            return None
        return {"access_token": d["access_token"], "polar_user_id": int(d["polar_user_id"])}

    def clear_token(self):
        with self._conn() as conn:
            conn.execute("DELETE FROM settings WHERE key IN ('access_token', 'polar_user_id')")

    # ── Normalisation helpers ──────────────────────────────────────────────

    @staticmethod
    def _parse_dt(value: str | None):
        if not value:
            return None
        return datetime.fromisoformat(value.replace("Z", "+00:00"))

    @staticmethod
    def _safe_num(value):
        if value is None:
            return None
        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _wake_count_from_hypnogram(hypnogram: dict | None) -> Optional[int]:
        """
        Polar hypnogram stage 0 means WAKE. The API does not provide a wake
        episode count, so count transitions into WAKE as a transparent proxy.
        """
        if not hypnogram:
            return None
        wake_count = 0
        previous = None
        for _, stage in sorted(hypnogram.items()):
            try:
                stage = int(stage)
            except (TypeError, ValueError):
                previous = stage
                continue
            if stage == 0 and previous != 0:
                wake_count += 1
            previous = stage
        return wake_count

    @staticmethod
    def _normalise_resp_rate(rec: dict) -> Optional[float]:
        """
        Store respiratory rate as breaths/minute.
        Current Nightly Recharge payload uses breathing_rate_avg directly.
        Older payloads may expose respiration interval in milliseconds.
        """
        breathing_rate = rec.get("breathing_rate_avg")
        if breathing_rate is not None:
            return float(breathing_rate)

        interval_ms = rec.get("meanNightlyRecoveryRespirationInterval") or rec.get("respirationInterval")
        if interval_ms:
            return round(60000 / float(interval_ms), 1)
        return None

    # ── Upserts ────────────────────────────────────────────────────────────

    def upsert_sleep_night(self, night: dict):
        d = night.get("date") or night.get("night")
        if not d:
            return

        sleep_start = night.get("sleep_start_time") or night.get("sleepStart")
        sleep_end = night.get("sleep_end_time") or night.get("sleepEnd")

        light_sleep = int(night.get("light_sleep") or 0)
        deep_sleep = int(night.get("deep_sleep") or 0)
        rem_sleep = int(night.get("rem_sleep") or 0)
        unrecognized = int(night.get("unrecognized_sleep_stage") or 0)
        asleep_sec = light_sleep + deep_sleep + rem_sleep + unrecognized

        span_sec = None
        try:
            start_dt = self._parse_dt(sleep_start)
            end_dt = self._parse_dt(sleep_end)
            if start_dt and end_dt:
                span_sec = int((end_dt - start_dt).total_seconds())
        except Exception:
            span_sec = None

        efficiency_pct = round(asleep_sec / span_sec * 100, 1) if asleep_sec and span_sec else None
        rem_pct = round(rem_sleep / asleep_sec * 100, 1) if asleep_sec else None
        deep_pct = round(deep_sleep / asleep_sec * 100, 1) if asleep_sec else None

        continuity = self._safe_num(night.get("continuity"))
        continuity_score = round(continuity * 20, 1) if continuity is not None else None

        wake_count = self._wake_count_from_hypnogram(night.get("hypnogram"))
        total_interruption_sec = night.get("total_interruption_duration")
        short_interruption_sec = night.get("short_interruption_duration")
        long_interruption_sec = night.get("long_interruption_duration")

        with self._conn() as conn:
            conn.execute("""
                INSERT INTO sleep_nights
                (date, sleep_score, continuity_score, efficiency_score, rem_score, n3_score,
                 sleep_span_sec, asleep_sec, efficiency_pct,
                 interruptions_total, interruptions_long, rem_pct, deep_pct,
                 sleep_start, sleep_end, raw_json,
                 total_interruption_sec, short_interruption_sec, long_interruption_sec,
                 wake_count, sleep_cycles, continuity_raw)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    sleep_score = EXCLUDED.sleep_score,
                    continuity_score = EXCLUDED.continuity_score,
                    efficiency_score = EXCLUDED.efficiency_score,
                    rem_score = EXCLUDED.rem_score,
                    n3_score = EXCLUDED.n3_score,
                    sleep_span_sec = EXCLUDED.sleep_span_sec,
                    asleep_sec = EXCLUDED.asleep_sec,
                    efficiency_pct = EXCLUDED.efficiency_pct,
                    interruptions_total = EXCLUDED.interruptions_total,
                    interruptions_long = EXCLUDED.interruptions_long,
                    rem_pct = EXCLUDED.rem_pct,
                    deep_pct = EXCLUDED.deep_pct,
                    sleep_start = EXCLUDED.sleep_start,
                    sleep_end = EXCLUDED.sleep_end,
                    raw_json = EXCLUDED.raw_json,
                    total_interruption_sec = EXCLUDED.total_interruption_sec,
                    short_interruption_sec = EXCLUDED.short_interruption_sec,
                    long_interruption_sec = EXCLUDED.long_interruption_sec,
                    wake_count = EXCLUDED.wake_count,
                    sleep_cycles = EXCLUDED.sleep_cycles,
                    continuity_raw = EXCLUDED.continuity_raw
            """, (
                d,
                night.get("sleep_score"),
                continuity_score,
                efficiency_pct,
                night.get("group_regeneration_score"),
                night.get("group_regeneration_score"),
                span_sec,
                asleep_sec,
                efficiency_pct,
                wake_count,
                long_interruption_sec,
                rem_pct,
                deep_pct,
                sleep_start,
                sleep_end,
                json.dumps(night),
                total_interruption_sec,
                short_interruption_sec,
                long_interruption_sec,
                wake_count,
                night.get("sleep_cycles"),
                continuity,
            ))

    def upsert_recovery(self, day: str, rec: dict):
        if not day:
            return
        resp_rate_bpm = self._normalise_resp_rate(rec)
        nightly_status = rec.get("nightly_recharge_status") or rec.get("recoveryIndicator")
        ans_charge_status = rec.get("ans_charge_status")

        with self._conn() as conn:
            conn.execute("""
                INSERT INTO nightly_recovery
                (date, rmssd, rri, recovery_indicator, recovery_sub_level,
                 ans_status, resp_interval_ms, raw_json,
                 resp_rate_bpm, heart_rate_avg, ans_charge_status)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    rmssd = EXCLUDED.rmssd,
                    rri = EXCLUDED.rri,
                    recovery_indicator = EXCLUDED.recovery_indicator,
                    recovery_sub_level = EXCLUDED.recovery_sub_level,
                    ans_status = EXCLUDED.ans_status,
                    resp_interval_ms = EXCLUDED.resp_interval_ms,
                    raw_json = EXCLUDED.raw_json,
                    resp_rate_bpm = EXCLUDED.resp_rate_bpm,
                    heart_rate_avg = EXCLUDED.heart_rate_avg,
                    ans_charge_status = EXCLUDED.ans_charge_status
            """, (
                day,
                rec.get("heart_rate_variability_avg") or rec.get("meanNightlyRecoveryRmssd") or rec.get("rmssd"),
                rec.get("beat_to_beat_avg") or rec.get("meanNightlyRecoveryRri") or rec.get("rri"),
                nightly_status,
                50 if nightly_status is not None else None,
                rec.get("ans_charge") or rec.get("ansStatus"),
                None,
                json.dumps(rec),
                resp_rate_bpm,
                rec.get("heart_rate_avg"),
                ans_charge_status,
            ))

    def upsert_activity(self, act: dict):
        day = act.get("date")
        if not day and act.get("start_time"):
            day = act["start_time"][:10]
        if not day and act.get("created"):
            day = act["created"][:10]
        if not day:
            return

        summary = act.get("summary", act)
        steps_obj = summary.get("steps") if isinstance(summary.get("steps"), dict) else None
        steps = summary.get("steps") if isinstance(summary.get("steps"), int) else None
        if steps is None and steps_obj:
            steps = steps_obj.get("total_steps")

        with self._conn() as conn:
            conn.execute("""
                INSERT INTO activity_days
                (date, steps, calories, met_minutes, active_calories, raw_json,
                 daily_activity, distance_from_steps, inactivity_alert_count)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    steps = EXCLUDED.steps,
                    calories = EXCLUDED.calories,
                    met_minutes = EXCLUDED.met_minutes,
                    active_calories = EXCLUDED.active_calories,
                    raw_json = EXCLUDED.raw_json,
                    daily_activity = EXCLUDED.daily_activity,
                    distance_from_steps = EXCLUDED.distance_from_steps,
                    inactivity_alert_count = EXCLUDED.inactivity_alert_count
            """, (
                day,
                steps,
                summary.get("calories"),
                summary.get("dailyMetMinutes") or summary.get("metMinutes"),
                summary.get("active_calories") or summary.get("activeCalories"),
                json.dumps(act),
                summary.get("daily_activity"),
                summary.get("distance_from_steps"),
                summary.get("inactivity_alert_count"),
            ))

    def upsert_hr_day(self, day: str, resting_hr: float | None, avg_hr: float | None, raw: dict):
        if not day:
            return
        with self._conn() as conn:
            conn.execute("""
                INSERT INTO hr_days (date, resting_hr, avg_hr, raw_json)
                VALUES (%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    resting_hr = EXCLUDED.resting_hr,
                    avg_hr = EXCLUDED.avg_hr,
                    raw_json = EXCLUDED.raw_json
            """, (day, resting_hr, avg_hr, json.dumps(raw)))

    def upsert_cardio_load(self, load: dict):
        day = load.get("date")
        if not day:
            return
        with self._conn() as conn:
            conn.execute("""
                INSERT INTO cardio_load_days
                (date, cardio_load_status, cardio_load, strain, tolerance, cardio_load_ratio, raw_json)
                VALUES (%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (date) DO UPDATE SET
                    cardio_load_status = EXCLUDED.cardio_load_status,
                    cardio_load = EXCLUDED.cardio_load,
                    strain = EXCLUDED.strain,
                    tolerance = EXCLUDED.tolerance,
                    cardio_load_ratio = EXCLUDED.cardio_load_ratio,
                    raw_json = EXCLUDED.raw_json
            """, (
                day,
                load.get("cardio_load_status"),
                load.get("cardio_load"),
                load.get("strain"),
                load.get("tolerance"),
                load.get("cardio_load_ratio"),
                json.dumps(load),
            ))

    # ── Reads ──────────────────────────────────────────────────────────────

    def log_sync(self, nights_added: int = 0, status: str = "ok", message: str = None):
        with self._conn() as conn:
            conn.execute(
                "INSERT INTO sync_log (synced_at, nights_added, status, message) VALUES (%s,%s,%s,%s)",
                (datetime.utcnow().isoformat(), nights_added, status, message),
            )

    def last_sync(self) -> Optional[str]:
        with self._conn() as conn:
            row = conn.execute(
                "SELECT synced_at FROM sync_log WHERE status IN ('ok','partial') ORDER BY id DESC LIMIT 1"
            ).fetchone()
        return row["synced_at"] if row else None

    def get_nights(self, days: int = 30) -> list:
        with self._conn() as conn:
            rows = conn.execute("""
                SELECT
                    s.date,
                    s.sleep_score,    s.continuity_score, s.efficiency_score,
                    s.rem_score,      s.n3_score,
                    s.sleep_span_sec, s.asleep_sec,       s.efficiency_pct,
                    s.interruptions_total, s.interruptions_long,
                    s.rem_pct,        s.deep_pct,
                    s.sleep_start,    s.sleep_end,
                    s.total_interruption_sec, s.short_interruption_sec, s.long_interruption_sec,
                    s.wake_count,     s.sleep_cycles,     s.continuity_raw,
                    r.rmssd,          r.rri,
                    r.recovery_indicator, r.recovery_sub_level,
                    r.ans_status,     r.resp_rate_bpm,    r.heart_rate_avg,
                    a.steps,          a.calories,         a.met_minutes,
                    a.active_calories, a.daily_activity,  a.distance_from_steps,
                    c.cardio_load_status, c.cardio_load, c.strain AS cardio_strain,
                    c.tolerance, c.cardio_load_ratio,
                    h.resting_hr,     h.avg_hr
                FROM sleep_nights s
                LEFT JOIN nightly_recovery r ON r.date = s.date
                LEFT JOIN activity_days    a ON a.date = s.date
                LEFT JOIN cardio_load_days c ON c.date = s.date
                LEFT JOIN hr_days          h ON h.date = s.date
                ORDER BY s.date DESC
                LIMIT %s
            """, (days,)).fetchall()
        return [dict(r) for r in reversed(rows)]

    def get_hypnogram_events(self, days: int = 30) -> list:
        with self._conn() as conn:
            rows = conn.execute("""
                SELECT date, sleep_start, sleep_end, raw_json
                FROM sleep_nights
                ORDER BY date DESC LIMIT %s
            """, (days,)).fetchall()
        return [dict(r) for r in rows]

    def get_latest_raw_samples(self) -> dict:
        with self._conn() as conn:
            tables = {
                "sleep": "sleep_nights",
                "recovery": "nightly_recovery",
                "activity": "activity_days",
                "hr": "hr_days",
                "cardio_load": "cardio_load_days",
            }
            out = {}
            for key, table in tables.items():
                row = conn.execute(f"SELECT date, raw_json FROM {table} ORDER BY date DESC LIMIT 1").fetchone()
                if not row:
                    out[key] = None
                    continue
                raw = json.loads(row["raw_json"])
                out[key] = {"date": row["date"], "keys": list(raw.keys()), "sample": raw}
            return out
